sudo: false
language: node_js
node_js:
  node
install:
  - npm install
  - npm install mocha-phantomjs-core
  - npm install -g browserify uglify-js
  - make clean
  - make
cache:
  directories:
    - node_modules
    - $HOME/.nvm
script:
  - phantomjs node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js test/index.html
notifications:
  email: false
