sudo: false
language: node_js
node_js:
  node
install:
  - npm install
  - npm install -g browserify uglify-js
  - make clean
  - make
cache:
  directories:
    - node_modules
    - $HOME/.nvm
script:
  - ./node_modules/.bin/mocha-headless-chrome -a no-sandbox -f test/index.html
notifications:
  email: false
